// ▼1. Ex1: BEEP BOOP
// ▲1. Ex1: BEEP BOOP

// ▼2. Ex2: USING NPM PACKAGES
// ▲2. Ex2: USING NPM PACKAGES

// ▼3. Ex3: SINGLE EXPORT
// ▲3. Ex3: SINGLE EXPORT

// ▼4. Ex4: MULTI EXPORT
// ▲4. Ex4: MULTI EXPORT

// ▼5. Ex5: BUILTINS
// ▲5. Ex5: BUILTINS

// ▼6. Ex6: BUILD A WIDGET
// ▲6. Ex6: BUILD A WIDGET

// ▼7. Ex7: USING TRANSFORMS
// ▲7. Ex7: USING TRANSFORMS

// ▼8. Ex8: WRITING TRANSFORMS
// ▲8. Ex8: WRITING TRANSFORMS

// ▼9. Ex9: WIDGET WITH ASSETS
// ▲9. Ex9: WIDGET WITH ASSETS

// ▼10. Ex10: SHIMMING NON-COMMONJS MODULES
// ▲10. Ex10: SHIMMING NON-COMMONJS MODULES